#!/usr/bin/python
# -*- coding: utf-8 -*-
#parsing data from EXFOR database at cdfe.sinp.msu.ru, Nov 2018
import requests
import re
import numpy as np

r = requests.get('http://cdfe.sinp.msu.ru/cgi-bin/exf2htm?LINK=M0744007&SOURCE=ON')
lines = r.text.split('\n')
i=0
for line in lines:
	if line.startswith('MEV        MB         MB') == True:
		break
	i=i+1
arr = r.text.split('\n')[i+1:-3]
arr = [re.sub(r'\s+', r' ', elem.lstrip().rstrip()).split() for elem in arr]

table = []
for elem in arr:
	if len(elem) == 5:
		table.append(elem[:2] + [0])
		
	else:
		table.append(elem[:3])

energy = np.float64(np.delete(table,[1,2],1)).ravel()
xs = np.float64(np.delete(table,[0,2],1)).ravel()
err = np.float64(np.delete(table,[0,1],1)).ravel()

f0 = open('experiment','w')
for i in range(len(energy)):
	f0.write(str(energy[i]) + '\t' + str(xs[i]) + '\t' + str(err[i]) + '\n')
f0.close()
